[tool.poetry]
name = "django-ajax-login"
version = "0.1.0"
description = ""
authors = ["Hugo Fernando Silva Álvarez <hugofer93@gmail.com>"]

[tool.poetry.dependencies]
python = "~3.8"
Django = "~2.2"

[tool.poetry.dev-dependencies]

[build-system]
